version: 1.0.{build}
build_script:
- ps: >-
    dotnet build GoogleCloudStorage.AspNetCore.DataProtection/GoogleCloudStorage.AspNetCore.DataProtection.csproj
after_test:
- ps: >-
    dotnet pack GoogleCloudStorage.AspNetCore.DataProtection/GoogleCloudStorage.AspNetCore.DataProtection.csproj -c Release --include-symbols
artifacts:
- path: GoogleCloudStorage.AspNetCore.DataProtection/bin/Release/*.nupkg
  name: GoogleCloudStorage.AspNetCore.DataProtection
deploy:
- provider: NuGet
  api_key:
    secure: HatA8lH7GwAGuVEwLUL8mYA29zB8SD+GfYZv2sowexXoJ9fezoT9F7xlZ7YeT7Eg
  skip_symbols: true